[build]
  base = "client"
  command = "CI= npm install --include=dev && npm run build"
  publish = "dist"

[build.environment]
  NODE_ENV = "development"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
